# Site
name: "The Margalla Today"
title: "The Margalla Today"
# description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: themargallatoday@gmail.com
site-twitter: "https://twitter.com/advraheemjamali"
site-youtube: "https://youtube.com/themargallatoday"
site-facebook: "https://facebook.com/themargallatoday"

# Authors
authors:
  raheemjamali:
    name: raheemjamali
    display_name: Raheem Jamali 
    avatar: 'assets/images/avatar-sal.png'
    email: raheemjamalipk@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/advraheemjamali
    description: "Founder & Editor-in-Chief of The Margalla Today, an aspiring young blogger from Islamabad, well versed in Law, Politics and Information Technology."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
